trigger:
- main

pool:
  vmImage: 'ubuntu-latest' 

variables:
  imageName: 'pipelines-javascript-docker'

steps:
 - task: DockerInstaller@0
   inputs:
    dockerVersion: '17.09.0-ce'
 - task: Docker@2
   displayName: Build an image
   inputs:
     repository: $(imageName)
     command: build
     Dockerfile: app/Dockerfile

 - task: ErmeticContainerImageScan@1
   inputs:
      apiToken: '$(TENABLE_API_TOKEN)'
      apiUrl: 'https://au.app.ermetic.com'
      name: 'pipelines-javascript-docker'
