trigger:
- main

pool:
  vmImage: 'ubuntu-latest' 

steps:
 - task: Docker@2
   displayName: Build an image
   inputs:
     repository: $(imageName)
     command: build
     Dockerfile: app/Dockerfile

variables:
  imageName: 
  - task: ErmeticContainerImageScan@1
    inputs:
      apiToken: '$(TENABLE_API_TOKEN)'
      apiUrl: 'https://au.app.ermetic.com'
      name: 'pipelines-javascript-docker'